const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    FETCH_GENRE_START: 'FETCH_GENRE_START',
    FETCH_GENRE_SUCCESS: 'FETCH_GENRE_SUCCESS',
    FETCH_GENRE_FAIL: 'FETCH_GENRE_FAIL',

    FETCH_SHOW_SUCCESS: 'FETCH_SHOW_SUCCESS',
    FETCH_SHOW_FAIL: 'FETCH_SHOW_FAIL',
    //lay tat nguoi dung va tao nguoi dung
    CREATE_USER_SUCESS: 'CREATE_USER_SUCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAIL: 'FETCH_ALL_USERS_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    EDIT_USER_SUCESS: 'EDIT_USER_SUCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',
    //lay tat ca phim va tao phim
    CREATE_FILM_SUCESS: 'CREATE_FILM_SUCESS',
    CREATE_FILM_FAIL: 'CREATE_FILM_FAIL',

    DELETE_FILM_SUCCESS: 'DELETE_FILM_SUCCESS',
    DELETE_FILM_FAIL: 'DELETE_FILM_FAIL',

    EDIT_FILM_SUCESS: 'EDIT_FILM_SUCESS',
    EDIT_FILM_FAIL: 'EDIT_FILM_FAIL',

    FETCH_TOP_FILMS_SUCCESS: 'FETCH_TOP_FILMS_SUCCESS',
    FETCH_TOP_FILMS_FAIL: 'FETCH_TOP_FILMS_FAIL',

    FETCH_ALL_FILMS_SUCCESS: 'FETCH_ALL_FILMS_SUCCESS',
    FETCH_ALL_FILMS_FAIL: 'FETCH_ALL_FILMS_FAIL',

    FETCH_NOW_SHOWING_FILMS_SUCCESS: 'FETCH_TOP_FILMS_SUCCESS',
    FETCH_NOW_SHOWING_FILMS_FAIL: 'FETCH_TOP_FILMS_FAIL',

    FETCH_COMING_SOON_SUCCESS: 'FETCH_TOP_FILMS_SUCCESS',
    FETCH_COMING_SOON_FAIL: 'FETCH_TOP_FILMS_FAIL',

    SAVE_INFOR_FILM_SUCESS: 'SAVE_INFOR_FILM_SUCESS',
    SAVE_INFOR_FILM_FAIL: 'SAVE_INFOR_FILM_FAIL',

    SAVE_BANNER_FILM_SUCESS: 'SAVE_BANNER_FILM_SUCESS',
    SAVE_BANNER_FILM_FAIL: 'SAVE_BANNER_FILM_FAIL',

    FETCH_BANNER_FILMS_SUCCESS: 'FETCH_BANNER_FILMS_SUCCESS',
    FETCH_BANNER_FILMS_FAIL: 'FETCH_BANNER_FILMS_FAIL',
    //NEWS
    CREATE_NEWS_SUCESS: 'CREATE_NEWS_SUCESS',
    CREATE_NEWS_FAIL: 'CREATE_NEWS_FAIL',

    FETCH_ALL_NEWS_SUCCESS: 'FETCH_ALL_NEWS_SUCCESS',
    FETCH_ALL_NEWS_FAIL: 'FETCH_ALL_NEWS_FAIL',

    DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS',
    DELETE_NEWS_FAIL: 'DELETE_NEWS_FAIL',

    EDIT_NEWS_SUCESS: 'EDIT_NEWS_SUCESS',
    EDIT_NEWS_FAIL: 'EDIT_NEWS_FAIL',

    FETCH_TOP_NEWS_SUCCESS: 'FETCH_TOP_NEWS_SUCCESS',
    FETCH_TOP_NEWS_FAIL: 'FETCH_TOP_NEWS_FAIL',
})

export default actionTypes;